Task_2_3_1
nocarend/OOP pull request #20
Opened 2023-03-20 17:26 UTC by nocarend

Грязный софт дедлайн, текущую версию точно не нужно запускать.

2023-04-11 04:22 UTC, nocarend commented
Потыкал по репозиториям со змейками, почему-то никто FXGL не использовал. В условии не запрещено, потому и юзал.

2023-04-18 17:38 UTC, shadrina reviewed
По поводу вопроса о необходимом усложнении. Будем следовать доп. условию:

> - на поле есть несколько таких же змеек, управляемых программой, обладающих разной стратегией поведения; 
> - в случае, если змейка пользователя пересекает другую змейку, то хвост другой змейки «отгрызается». Если это голова, то змейка съедается полностью.

По поводу "разной стратегии поведения" можно включить фантазию. Сходу напрашивается стратегия, при которой робо-змейка старается кратчайшим путем заполучить еду. Или кратчайшим путем уничтожить змейку пользователя. Алгоритм нахождения кратчайшего пути от точки A до точки B на 2D поле на твой выбор.

Ну и всякие дополнительные самопридуманные навороты, компенсирующие использование FXGL, только приветствуются.

2023-04-18 19:45 UTC, nocarend commented
понятно

2023-04-25 15:02 UTC, nocarend commented
Мне кажется, что "передвигается по полю «N» x «M»;" имеется ввиду, что мы сами выбираем это N и M.
Иначе, нужно для каждого разрешения генерировать набор уровней, что в теории можно быстро сделать, но, кажется, что это не то, что нужно.

2023-04-25 15:03 UTC, nocarend commented
Выбор L добавил как CheckBox в доп. классе.

2023-05-01 12:59 UTC, shadrina requested changes
1) Она не билдится
2) Если аргумент про N и M еще хоть как-то прокатывает, то про еду нет. В условии написано => надо

2023-05-01 14:06 UTC, nocarend commented
Понятно, создам новый пулл реквест. Может там забилдится.

2023-05-01 14:07 UTC, closed without merging